#! /usr/bin/env python3
# coding: utf-8

##
## EPITECH PROJECT, 2020
## B-YEP-410-BDX-4-1-zappy-jimmy.kohl
## File description:
## zappy_ia
##

from main import main

if __name__ == "__main__":
    main()

